### PR TITLE
Fix make not create scopedRegistry when scopes are empty

### LINKED ISSUE #134: Do not create scopedRegistry when scopes are empty
I am running the following command for automated testing of my UPM packages.
```
openupm -c $(PROJECT_HOME) add -ft MY_PACKAGE_NAME@file:../../
```

Created manifest.json is:
```
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": []
    }
  ],
  "testables": [
    "MY_PACKAGE_NAME"
  ]
```

An error occurred when opening this project:
```
[Package Manager] Registry configuration is invalid:
  Scoped registry at position 1 is invalid:
    "scopedRegistries[0].scopes" must contain at least 1 items
[Package Manager] Failed to update project manifest: Registry configuration is invalid:
  Scoped registry at position 1 is invalid:
    "scopedRegistries[0].scopes" must contain at least 1 items
```

This issue occurs in v1.19.6. The manifest.json at v1.17.0 was as follows:
```
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.openupm"
      ]
    }
  ],
  "testables": [
    "MY_PACKAGE_NAME"
  ]
```

In v1.17.0, scopes existed, so there was no problem.

### PR DESCRIPTION
**Pull request by nowsprinting**
### Changes
Not create scopedRegistry when scopes are empty.
Possible when specified `@git`, `@htts`, and `@file` with `add` subcommand.

fixed #134

### CODE REVIEW

File: test/test-cmd-add.ts [hunk 1]
```diff
@@ -262,6 +262,9 @@ describe("cmd-add.ts", function () {
       await mockProject.tryAssertManifest((manifest) =>
         shouldHaveDependency(manifest, packageA, fileUrl)
       );
+      await mockProject.tryAssertManifest((manifest) =>
```
Comment (favoyang) [inline test/test-cmd-add.ts:265]: Let's add the same assert for tests `"add pkg@http"` and `"add pkg@git"`.

**Review by favoyang — CHANGES_REQUESTED** [review]

**Comment by favoyang** [comment]
@all-contributors please add @nowsprinting for code and bug.

File: test/test-cmd-add.ts (hunk 1 above)
Comment (nowsprinting) [reply test/test-cmd-add.ts:271]: Fixed in 80ac9b2

**Review by favoyang — APPROVED** [review]
LGTM
